import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopBar from './components/TopBar/TopBar'
import Head from './head'
import { ActionsProvider } from '@/context/ActionsContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Matheus Rodrigues',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head />
      <ActionsProvider>
        <body className={inter.className}>
          <TopBar />
          {children}
        </body>
      </ActionsProvider>
    </html>
  )
}
